version: '3'
services:
  # mariadb:
  #   image: bitnami/mariadb:10.6
  #   ports:
  #     - "3306"
  #   environment:
  #     - MARIADB_USER=bn_moodle
  #     - MARIADB_PASSWORD=foobar1111
  #     - MARIADB_ROOT_PASSWORD=foobar1111
  #     - MARIADB_DATABASE=bitnami_moodle
  #     - MARIADB_CHARACTER_SET=utf8mb4
  #     - MARIADB_COLLATE=utf8mb4_unicode_ci
  #   volumes:
  #     - './mariadb_data:/bitnami/mariadb'
  moodle:
    image: bitnami/moodle:3
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - BITNAMI_DEBUG=true
      - MOODLE_DATABASE_HOST=182.184.67.82
      - MOODLE_DATABASE_PORT_NUMBER=9033
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=moodle
      - MOODLE_DATABASE_ROOT_PASSWORD=moodle
      # - MOODLE_SITE_NAME=Moodle v3 Test 1
      - MOODLE_USERNAME=moodle
      - MOODLE_PASSWORD=moodle
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    # depends_on:
    #   - mariadb
volumes:
  # mariadb_data:
  moodle_data:
  moodledata_data: